# Flight Tracker to India
# Tracks flight deals and information for flights to India

param(
    [string]$From = "USA",
    [string]$To = "India",
    [switch]$SaveResults,
    [switch]$PublishToFile
)

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  FLIGHT TRACKER TO INDIA" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Get current date for the report
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$fileTimestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"

Write-Host "Route: $From to $To" -ForegroundColor Yellow
Write-Host "Time: $timestamp" -ForegroundColor Gray
Write-Host ""
Write-Host "Querying AI for flight information..." -ForegroundColor Gray
Write-Host ""

# Construct the query
$query = "I need information about flights from $From to $To. Please provide: 1) Best booking websites for this route 2) Typical price ranges 3) Best months to travel for cheap fares 4) Best days of the week to fly 5) Popular airlines for this route 6) Average flight duration 7) Tips for finding deals. Keep it practical and organized."

# Query Moltbot
try {
    Write-Host "AI is analyzing flight data..." -ForegroundColor Cyan
    $result = clawdbot agent --to +1234567890 --message $query --local 2>&1 | Out-String
    
    Write-Host ""
    Write-Host "======================================" -ForegroundColor Green
    Write-Host "  FLIGHT INFORMATION REPORT" -ForegroundColor Green
    Write-Host "======================================" -ForegroundColor Green
    Write-Host ""
    Write-Host $result
    Write-Host ""
    
    # Save results if requested
    if ($SaveResults -or $PublishToFile) {
        $reportFile = "flight-report-$fileTimestamp.txt"
        
        $report = @"
======================================
FLIGHT TRACKER TO INDIA
======================================
Route: $From to $To
Generated: $timestamp

$result

======================================
Generated by Moltbot AI
======================================
"@
        
        $report | Out-File -FilePath $reportFile -Encoding UTF8
        Write-Host "Report saved to: $reportFile" -ForegroundColor Green
        Write-Host ""
        
        # Also create a latest.txt for easy access
        $report | Out-File -FilePath "flight-report-latest.txt" -Encoding UTF8
        Write-Host "Latest report: flight-report-latest.txt" -ForegroundColor Cyan
    }
    
    Write-Host ""
    Write-Host "Flight tracking complete!" -ForegroundColor Green
    Write-Host ""
    
} catch {
    Write-Host "Error querying AI: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Make sure the gateway is running:" -ForegroundColor Yellow
    Write-Host "  clawdbot gateway" -ForegroundColor Gray
    exit 1
}

# Show usage tips
Write-Host "USAGE TIPS:" -ForegroundColor Yellow
Write-Host ""
Write-Host "Track specific routes:" -ForegroundColor White
Write-Host '  .\flight-tracker-india.ps1 -From "New York" -To "Mumbai"' -ForegroundColor Gray
Write-Host ""
Write-Host "Save results to file:" -ForegroundColor White
Write-Host '  .\flight-tracker-india.ps1 -SaveResults' -ForegroundColor Gray
Write-Host ""
Write-Host "Publish report:" -ForegroundColor White
Write-Host '  .\flight-tracker-india.ps1 -PublishToFile' -ForegroundColor Gray
Write-Host ""
